{
 "title": "KNI Performance Dashbaord",
 "description": "Performance dashboard for Red Hat - RHHI.next",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Basic : Master-0",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.111.20:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"192.168.111.20:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.111.20:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.111.20:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.111.20:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.111.20:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-1",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.111.21:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"192.168.111.21:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.111.21:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.111.21:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.111.21:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.111.21:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "CPU Basic : Master-2",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"192.168.111.22:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"192.168.111.22:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"192.168.111.22:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"192.168.111.22:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"192.168.111.22:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"192.168.111.22:9100\",job=~\".*\"}[1m])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic : Master-0",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"} - node_memory_MemFree_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"} - node_memory_SwapFree_bytes{instance=~\"192.168.111.20:9100\",job=~\".*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Basic : Master-1",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"} - node_memory_MemFree_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"} - node_memory_SwapFree_bytes{instance=~\"192.168.111.21:9100\",job=~\".*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Memory Basic : Master-2",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"} - node_memory_MemFree_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"} - (node_memory_Cached_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"} + node_memory_Buffers_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"} - node_memory_SwapFree_bytes{instance=~\"192.168.111.22:9100\",job=~\".*\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk IO : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"nvme.*\",instance=\"192.168.111.20:9100\"}[1m])",
     "legendFormat": "master-0 - {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"nvme.*\",instance=\"192.168.111.21:9100\"}[1m])",
     "legendFormat": "master-1 - {{device}}"
    }
   ]
  },
  {
   "title": "Disk IO : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"nvme.*\",instance=\"192.168.111.22:9100\"}[1m])",
     "legendFormat": "master-2 - {{device}}"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.111.20:9100\",device=~\"br.*|en.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.111.21:9100\",device=~\"br.*|en.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Utilization : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"192.168.111.22:9100\",device=~\"br.*|en.*\"}[5m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"192.168.111.20.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"192.168.111.21.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "Process RSS : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=~\".*\",endpoint=~\".*\",instance=~\"192.168.111.22.*\"}",
     "legendFormat": "{{ service }} - {{ job }}"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-0",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",node=\"master-0\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",node=\"master-1\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "OSD Memory Usage : Master-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{pod_name=~\"rook-ceph-osd.*\",node=\"master-2\",container_name=\"osd\"}",
     "legendFormat": "{{pod_name}} - RSS"
    }
   ]
  },
  {
   "title": "CPU Usage : Master-0",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{node=\"master-0\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU Usage : Master-1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{node=\"master-1\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "CPU  Usage : Master-2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{node=\"master-2\"}[5m])",
     "legendFormat": "{{ pod_name }} - {{ service }}"
    }
   ]
  },
  {
   "title": "Number of PVCs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_persistentvolumeclaim_info)\n",
     "legendFormat": "PVC Count"
    }
   ]
  },
  {
   "title": "Per-OSD Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate ( ceph_osd_op_r_in_bytes{ceph_daemon=~\"osd.*\"}[5m] ) ",
     "legendFormat": "{{ceph_daemon}} Read OPs"
    },
    {
     "expr": "irate ( ceph_osd_op_w_in_bytes{ceph_daemon=~\"osd.*\"}[5m] ) ",
     "legendFormat": "{{ceph_daemon}} Write OPs"
    },
    {
     "expr": "irate ( ceph_osd_op_r_in_bytes{ceph_daemon=~\"osd.*\"}[5m] )",
     "legendFormat": "{{ceph_daemon}} Read-modify-write  OPs"
    }
   ]
  },
  {
   "title": "etcd cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=\"etcd-metrics\"}[1m]))",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum by (container_name) (rate(container_cpu_usage_seconds_total{container_name=\"etcd-member\"}[1m]))",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Distribution",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(kube_pod_info{ node=\"master-0\"}) \n",
     "legendFormat": "master-0"
    },
    {
     "expr": "sum(kube_pod_info{node=\"master-1\"})\n",
     "legendFormat": "master-1"
    },
    {
     "expr": "sum(kube_pod_info{node=\"master-2\"})\n",
     "legendFormat": "master-2"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Failed Rest Client Request from KubeCTL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 * sum by(instance, job) (rate(rest_client_requests_total{code!~\"2..\"}[5m]))/ sum by(instance, job) (rate(rest_client_requests_total[5m]))"
    }
   ]
  }
 ]
}